version: "3"
services:
  postgres:
    image: bitnami/postgresql:12.11.0
    ports:
      - 5449:5432
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRESQL_EXTRA_FLAGS: "-c random_page_cost=1.1 -c work_mem=16MB"
    volumes:
      - postgres:/bitnami/postgresql
  minio:
    image: minio/minio:RELEASE.2020-08-18T19-41-00Z
    ports:
      - 9009:9000
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7PROKNOW
      MINIO_SECRET_KEY: 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
    volumes:
      - minio:/export
    command: server /export
  redis:
    image: redis:6.0-alpine
    ports:
      - 6399:6379
  keycloak:
    build: ./keycloak
    ports:
      - 8289:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    volumes:
      - keycloak:/opt/keycloak/data
  proknow-init:
    image: proknow.azurecr.io/proknow:2.0.2-alpha.1-20240521.205803-676a34b
    command: "upgrade --config /etc/opt/proknow/config.json"
    depends_on:
      - postgres
      - minio
      - redis
      - keycloak
    volumes:
      - ./pk-etc:/etc/opt/proknow
  proknow:
    image: proknow.azurecr.io/proknow:2.0.2-alpha.1-20240521.205803-676a34b
    depends_on:
      - proknow-init
    environment:
      PATIENTS_MIN_PAGE_SIZE: 1
    volumes:
      - ./pk-etc:/etc/opt/proknow
      - proknow-opt:/var/opt/proknow
  rt-visualizer:
    image: epgcr.azurecr.io/rt-visualizer:0.9.0
    ports:
      - 8998:8988
    volumes:
      - rt-visualizer-cache:/etc/opt/rt-visualizer/cache/
      - ./rtv-etc:/etc/opt/rt-visualizer/config/
      - ./certs:/etc/opt/rt-visualizer/certs
    entrypoint:
      [
        "/opt/rt-visualizer/server",
        "--config",
        "/etc/opt/rt-visualizer/config/config.json"
      ]
  nginx:
    image: nginx:latest
    ports:
      - 3005:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rt-visualizer
      - proknow
volumes:
  keycloak:
  postgres:
  minio:
  proknow-opt:
  rt-visualizer-cache:
